#!/usr/bin/perl

while (<>) {
	next if $seen{$_};
	$seen{$_} = 1;
	chomp;

	s/\$[0-9,]+k//ig;
	s/\$[0-9,]+ deposit//ig;

	if (/\$([0-9,]+)/) {
		$price = $1;
		$price =~ s/,//g;

		if ($price > 0) {
			print "$price $_\n";
		}
	}
}
