#!/bin/sh

# http://www.bls.gov/cew/datatoc.htm

for i in {1975..1983}
do
	echo $i
	cat "sic.$i.annual.by_area/sic.$i.annual 06075 (San Francisco County, California).csv" |
	grep 'County, 2-digit SIC.*All establishment sizes' |
	./csv  |
	awk -F, '($15 != 0) {print $6 "," $15 "," $16 "," $16 / $15 ",zzz " $11}' |
	sort -t, -n -k4 |
	awk -F, 'BEGIN {prev = 0} {people_sum += $2; print $2, people_sum, prev, $4, $5; prev = $4}' |
	sed 's/zzz //' > distrib-$i
done

for i in {1984..2000}
do
	echo $i
	cat "sic.$i.annual.by_area/sic.$i.annual 06075 (San Francisco County, California).csv" |
	grep 'County, 4-digit SIC.*All establishment sizes' |
	./csv  |
	awk -F, '($15 != 0) {print $6 "," $15 "," $16 "," $16 / $15 ",zzz " $11}' |
	sort -t, -n -k4 |
	awk -F, 'BEGIN {prev = 0} {people_sum += $2; print $2, people_sum, prev, $4, $5; prev = $4}' |
	sed 's/zzz //' > distrib-$i
done

for i in {2001..2014}
do
	echo $i
	cat $i".annual.by_area/$i.annual 06075 San Francisco County, California.csv" |
	grep 'County, NAICS 6-digit -- by ownership sector.*All establishment sizes' |
	./csv |
	awk -F, '($15 != 0) {print $6 "," $15 "," $16 "," $16 / $15 ",zzz " $11}' |
	sort -t, -n -k4 |
	awk -F, 'BEGIN {prev = 0} {people_sum += $2; print $2, people_sum, prev, $4, $5; prev = $4}' |
	sed 's/zzz //' > distrib-$i
done


